apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: w1g8ii8w8-python-gitops
  description: This is GitOps manifest for w1g8ii8w8-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=w1g8ii8w8-python
    backstage.io/kubernetes-id: w1g8ii8w8-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: w1g8ii8w8-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:w1g8ii8w8-python
